// This file is auto-generated by Lovable. Do not modify it.

import type { OAuthProvider } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: OAuthProvider, opts?: SignInOptions) => {
      try {
        const { error } = await supabase.auth.signInWithOAuth({
          provider: provider as "google" | "github",
          options: {
            ...(opts?.redirect_uri ? { redirectTo: opts.redirect_uri } : {}),
            ...(opts?.extraParams ? { queryParams: opts.extraParams } : {}),
          },
        });

        if (error) {
          return { error };
        }

        return { redirected: true };
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
    },
  },
};
